version: '3.8'

services:
  lambda_tester:
    # Use the name you gave your Docker image during the build step
    build: .
    image: lambda-endpoint-tester:latest

    env_file:
      - .env

    ports:
       - "8080:8080"

    # Optional: You can explicitly define environment variables here as well.
    # environment:
    #   - LOG_LEVEL=INFO